### ISSUE TITLE
Length of children

### ISSUE THREAD

**Issue by atroche** [Prismatic/dommy#94]
Hey guys,

Currently `(count (children (dommy/sel1 :body)))` throws `[object HTMLCollection] is not ISeqable`. Is there an easy way to make it so that it *is* ISeqable?

Cheers!

**Comment by erikprice** [comment]
Take a look at [`dommy.utils/->Array`](https://github.com/Prismatic/dommy/blob/master/src%2Fdommy%2Futils.cljs#L14-L15). This returns a JS array object, so there are some operations for which you may still have to use `js->clj`:
```clj
(-> my-children-node u/->Array sequential?) ;; => false
(-> my-children-node u/->Array js->clj sequential?) ;; => true
```

**Comment by loganlinn** [comment]
dommy aims to be a thin DOM API in this regard by always returning native objects, where applicable. I would suggest using `(alength (children (dommy/sel1 :body)))`
